### ISSUE TITLE
Yet another password problem

### ISSUE THREAD

**Issue by sebie** [Tox/toxme.se#22]
I created an account on toxme with a username `sebie` and like a few others, I am having trouble editing it. The error I get says it is a password problem although I copied it when I initially created my account.

Because it is a fresh install of Tox I (should) have all the things to prove that the account *is* mine. 

The Tox ID on the Toxme page is correct, thus if need be you can contact me through Tox.

Thank you!

**Comment by EmilyLPillmore** [comment]
Ooooo look at me, i'm sebie and i'm so cool i'm opening up a brand new ticket for some trivial dumb stuff that no one cares about ooooo

**Comment by stal888** [comment]
lmao @EmilyLPillmore

**Comment by sebie** [comment]
Just checking, has it been fixed? If so, thank you ( @stqism ).

**Comment by sebie** [comment]
I noticed that you are closing down issues. Is it on a `todo` list or something? Like stated above. I should all the required keys to prove it is mine.

**Comment by stal888** [comment]
GSoC slave will save you

**Comment by sebie** [comment]
(Sorry, don't know who / what that is..). If it a person, thank them?

**Comment by stal888** [comment]
I don't know who it will be either but I will thank them for you.

These issues shouldn't be closed before they are fixed though.

**Comment by sebie** [comment]
Wait wouldn't you fix it as you are the owner? If not, could you reopen it then?

And I will repeat myself; as said above, I still (should) have the keys to prove it is my account.

**Comment by itsrachelfish** [comment]
I agree, this issue should remain issue until the GSoC slave completes the task. Then it is their victory to push the button!!

**Comment by stqism** [comment]
This issue tracker isn't for support issues.

A bug for this was assigned [toxme-2](https://issues.tox.im/youtrack/issue/toxme-2)

**Comment by itsrachelfish** [comment]
Reopening this issue because @stqism is a jerk and this is still an issue

**Comment by stqism** [comment]
@itsrachelfish Rude! 

Regardless, my wip efforts at fixing this require access to an account though so like lmao.

Might write a quick bot for ID based recovery but Tox's a bit iffy on reliability with a ton of users so I've been mostly avoiding that idea.

**Comment by sebie** [comment]
@itsrachelfish @stqism I don't want you guys to start arguing here about the domain and how donations where "stole[n]". To be honest, all I want is Tox to thire as a FOSS. 

Thanks.

**Comment by stqism** [comment]
@sebie If you need something quick you can easily edit your record using https://github.com/ToxMe/PyToxme on the command line if you know a little Python, just need access to the data file for authentication.

If you really want though later today I might have enough time to quickly spin up a script to change entries.

You did inspire me about a new API call though, something to generate a new password.

**Comment by sebie** [comment]
@stqism Sure, I'll wait. Regardless on the current situation I just want to resolve this issue.

**Comment by nurupo** [comment]
@sebie Would be nice if you could reopen the issue in the currently maintained repo (see the updated README.md file), if you haven't done that already.
